### ISSUE TITLE
Plugin crashes Wordpress Frontend on Wordpress 5.4.1 if an option to protect pages is checked without entering API key

### ISSUE THREAD

**Issue by nexus1703** [liblynx-llc/liblynx-wordpress-plugin#1]
Hello,
I have installed and activated the plugin on Wordpress 5.4.1 and it crashes the frontend with no other message then the generic message given if no API key is entered and pages are selected for protection by LibLynx.
I use Ubuntu 20.04 with php7.4 and mysql8.
I have tried both with vanilla wordpress installation (no plugin, no theme) and with loaded wordpress (woocommerce, theme etc).
Backend doesn't seem to be affected when the pugin
I don't see any log any where to find what is really going wrong, even with debug mode on.
If no protection is selected, the plugin doesn't seem to crash the frontend.

**Comment by lordelph** [comment]
Can you elaborate on the "crash" - what do you see in the browser for the frontend request, paste contents of webserver error log also. If you're interested in using LibLynx and don't have an API key, contact us at support@liblynx.com and we can assist you further.

**Comment by nexus1703** [comment]
Ok many thanks for your quick answer. I've dig up a bit more. The "crash" only happens if I try to protect "all pages and posts" or "All pages except flagged pages and posts" without having an API key.
I get the following error message in the debug plugin:
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array
in /var/www/html/wp-content/plugins/liblynx/classes/Client.php on line 118

Call stack:

LibLynx\Client::callAPI()
wp-content/plugins/liblynx/classes/Client.php:141
LibLynx\Client::apiPOST()
wp-content/plugins/liblynx/classes/Client.php:170
LibLynx\Client::authorize()
wp-content/plugins/liblynx/liblynx-connect.php:126
liblynx_template_redirect()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-includes/template-loader.php:13
require_once()
wp-blog-header.php:19
require()
index.php:17

I have entered wrong credentials to get this and setup Protect All pages and posts.
I think it can't connect to the LibLynx server so resorts to an exception but it's not intercepted by the standard loop in wordpress. So resorts to a crash.

**Comment by lordelph** [comment]
Will close this now - an incorrect API key had been entered.
